INSERT INTO table_info
    (id, name, version)
VALUES
    ('1', 'account', '1')
    ('2', 'auth_info', '2')
    ('3', 'hitokoto', '3')
    ('4', 'account_register', '4')
    ('5', 'author', '11')
    ('6', 'book_info', '12')
    ('7', 'license', '13')
    ('8', 'book', '14')
    ('9', 'sentence', '15')
    ('10', 'comment', '16')
    ('11', 'subtitle', '20')
    ('12', 'menu', '21')
    ('13', 'donation', '31')
    ('14', 'table_info', '101')
